characters = [
    {
        "index": 0,
        "class": "bard",
        "ilvl-endless": 1490,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "scrapper",
        "ilvl-endless": 1490,
        "ilvl-aor": 1540,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "bard",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "bard",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "bard",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "bard",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "bard",
        "ilvl-endless": 1100,
        "ilvl-aor": 1100,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    }
]
